name: Deploy to S3

on:
  push:
    branches:
      - main  # or replace with your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install AWS CLI via pip
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install awscli

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          source venv/bin/activate
          aws s3 sync . s3://14fsqn.co.uk --delete --region $AWS_REGION

